import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { GridPattern } from "@/components/ui/grid-pattern";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "AB Memon",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-w-screen min-h-screen flex flex-col`}
            >
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <div className="flex-1 relative max-w-screen-8xl mx-auto w-full h-full">
                        <main className="relative w-full h-full">
                            <GridPattern
                                width={20}
                                height={20}
                                x={100}
                                y={100}
                                className={cn("[mask-image:radial-gradient(400px_circle_at_center,white,transparent)]")}
                            />
                            {children}
                        </main>
                        <Toaster />
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
